name: CI/CD PPDB Makassar

on:
  push:
    branches: [ "main" ]

jobs:
  deploy-to-server:
    runs-on: self-hosted # PC Kantor Diskominfo

    steps:
    - name: 1. Izin Akses Folder Git (Safe Directory)
      shell: cmd
      run: git config --global --add safe.directory D:/Projects/spmb-makassar-devops

    - name: 2. Tarik Kode Terbaru dari GitHub
      shell: cmd
      run: |
        cd /d D:\Projects\spmb-makassar-devops
        git fetch --all
        git reset --hard origin/main

    - name: 3. Smart Rebuild (Hanya Update API)
      shell: cmd
      run: |
        cd /d D:\Projects\spmb-makassar-devops
        # Perintah ini hanya merefresh container API tanpa mematikan DB
        docker-compose up -d --build --no-deps api