name: CI/CD PPDB Makassar

on:
  push:
    branches: [ "main" ]

jobs:
  test-and-build:
    runs-on: self-hosted # Menggunakan PC Windows Kantor

    steps:
    # Langkah 1: Langsung masuk ke folder project di Drive D dan paksa update kode
    - name: Pull Kode Terbaru dari GitHub
      run: |
        cd /d D:\Projects\spmb-makassar-devops
        git fetch --all
        git reset --hard origin/main

    # Langkah 2: Biarkan Docker yang mengurus Python, Database, dan Build Image
    - name: Rebuild & Restart Server
      run: |
        cd /d D:\Projects\spmb-makassar-devops
        docker-compose down
        docker-compose up -d --build