name: CI/CD PPDB Makassar

on:
  push:
    branches: [ "main" ]

jobs:
  test-and-build:
    runs-on: self-hosted

    steps:
    - name: Pull Kode Terbaru dari GitHub
      shell: cmd
      run: |
        cd /d D:\Projects\spmb-makassar-devops
        git fetch --all
        git reset --hard origin/main

    - name: Rebuild & Restart Server
      shell: cmd
      run: |
        cd /d D:\Projects\spmb-makassar-devops
        docker-compose down
        docker-compose up -d --build